In [2]:
import cv2
import numpy as np

In [3]:
img=cv2.imread('photo/cat.jpeg')
cv2.imshow('original',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
B,G,R=cv2.split(img)

In [5]:
zeros=np.zeros(img.shape[:2],dtype='uint8')

In [6]:
img.shape[1]

260

In [7]:
img.shape[0]

194

In [8]:
cv2.imshow('red',cv2.merge([zeros,zeros,R]))
cv2.waitKey(0)

-1

In [9]:
cv2.imshow('green',cv2.merge([zeros,G,zeros]))
cv2.waitKey(0)

-1

In [10]:
cv2.imshow('red',cv2.merge([B,zeros,zeros]))
cv2.waitKey(0)

-1

In [11]:
B

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [12]:
G

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [13]:
R

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)